/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import waterspace.ElementType;
import waterspace.Position;
import waterspace.WorldElement;
import waterspace.WorldManager;
/**
 *
 * @author Administrateur
 */
public class MainFrame extends javax.swing.JFrame {

    private final WorldManager wm;
    public JLabel[][] gridLab;

    MainFrame(WorldManager wm) {
        this.wm = wm;
    }

    /**
     * Creates new form GUI_Game
     */
    public void setParam(int nbrX, int nbrY) {
        initComponents();
        setSize(800, 700);
        GridLayout grid = new GridLayout(nbrX, nbrY);
        panel_game.setLayout(grid);
        gridLab = new JLabel[nbrX][nbrY];
        for (int x = 0; x < nbrX; x++) {
            for (int y = 0; y < nbrY; y++) {
                gridLab[x][y] = new JLabel();

                //gridLab[x][y].setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/empty.png")));

                panel_game.add(gridLab[x][y]);
            }
        }
    }
    
    public void endGame(){
        JOptionPane.showMessageDialog(null, "The game is finished!");
    }
    
    public void refresh(ArrayList<WorldElement> elementList) {
        for (int x = 0; x < gridLab.length; x++) {
            for (int y = 0; y < gridLab[x].length; y++) {
                gridLab[x][y].setOpaque(false);
                boolean found = false;
                Position p = new Position(x,y,null);
                for (WorldElement worldElement : elementList) {
                    if(worldElement.getPosition().equals(p)){
                        if(worldElement.getType() == ElementType.WATER_ICE){
                            gridLab[x][y].setOpaque(true);
                            gridLab[x][y].setBackground(new Color(180, 216, 231));
                            //gridLab[x][y].setText("ICE");
                        } else{
                            ImageIcon image = new javax.swing.ImageIcon(getClass().getResource(worldElement.getImage()));
                            gridLab[x][y].setIcon(image);
                        }
                        found = true;
                    }
                }
                if (!found) {
                    
                    gridLab[x][y].setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/empty.png")));
                    //gridLab[x][y].setOpaque(true);
                    //gridLab[x][y].setBackground(new Color(51,102,153));
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_game = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bt_stepByStep = new javax.swing.JButton();
        bt_start = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        lbSideImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel_gameLayout = new javax.swing.GroupLayout(panel_game);
        panel_game.setLayout(panel_gameLayout);
        panel_gameLayout.setHorizontalGroup(
            panel_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        panel_gameLayout.setVerticalGroup(
            panel_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_game);

        jPanel1.setBackground(new java.awt.Color(2, 102, 245));

        bt_stepByStep.setText("StepByStep");
        bt_stepByStep.setToolTipText("");
        bt_stepByStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stepByStepActionPerformed(evt);
            }
        });

        bt_start.setText("Start Game");
        bt_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startActionPerformed(evt);
            }
        });

        bt_exit.setText("Exit");
        bt_exit.setToolTipText("");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSideImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_stepByStep, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_start, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_stepByStep)
                .addGap(58, 58, 58)
                .addComponent(bt_start)
                .addGap(46, 46, 46)
                .addComponent(bt_exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSideImage))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startActionPerformed
             // TODO add your handling code here:
        wm.runsim();
    }//GEN-LAST:event_bt_startActionPerformed

    private void bt_stepByStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stepByStepActionPerformed
        wm.executeNextStep();
    }//GEN-LAST:event_bt_stepByStepActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_exitActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_start;
    private javax.swing.JButton bt_stepByStep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSideImage;
    private javax.swing.JPanel panel_game;
    // End of variables declaration//GEN-END:variables

    public void displayEndofGame() {
        JOptionPane.showMessageDialog(panel_game,"End of game");
    }
}
